baseURL = 'https://callmephilip.com/'
languageCode = 'en-us'
title = 'callmephilip'
theme = 'archie'
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    Description="Words and codes from Philip Nuzhnyy, software developer"
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/callmephilip"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/callmephilip"
