baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'callmephilip'
theme = 'archie'
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

