baseURL = 'https://callmephilip.github.io/'
languageCode = 'en-us'
title = 'callmephilip'
theme = 'archie'
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/callmephilip"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/callmephilip"
